[project]
name = "autodefine-cn-vn"
version = "0.1.0"
description = "Automatically define Anki cards with Vietnamese definitions for Chinese vocabulary."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
